---
# https://docs.ansible.com/ansible/latest/modules/apt_module.html

- name: Updating the apt cache
  apt:
    update_cache: yes
  register: aptcacheresult
  retries: 5 # Looks like APT Cache can fail from time to time
  #until: aptcache.changed or aptcache.msg != "Failed to update apt cache: "
  delay: 2
  until:  aptcacheresult is succeeded

# Since we cannot exclude packages from the updating procedure, we need to make sure they're marked as holded (marks packages ineligible for automatic updates)
- name: Marking packages as ineligible for automatic updates
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
  - "{{ package_manager_excluded_packages }}"

# Then we make sure all the needed packages are installed
- name: Ensuring required packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ package_manager_needed_packages }}"

# Finally we do a dist-upgrade (so we upgrade the kernel too).
# 
- name: Installing all lastest version of packages
  apt:
    name: "*"
    state: latest

- name: Removing dependencies that are no longer required
  apt:
    autoremove: yes
  when: package_manager_apt_do_autoremove|bool

# We need another install because we want  to keep 1 "spare" kernel installation if possible
#  Autoremove would remove it 

- name: Installing the latest kernel version
  apt:
    upgrade: dist # Needed since we want to upgrade the kernel

- name: Check if reboot is required (probably due to a kernel update) # Tho Ubuntu likes to be rebooted anyway
  stat:
    path: /var/run/reboot-required
  register: need_reboot_query
  when: server_reboot_allowed|bool

- name: setting fast for rebooting
  set_fact: needs_reboot=True
  when: need_reboot_query is defined and need_reboot_query.stat.exists|bool

